services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: peaks
      POSTGRES_PASSWORD: peaks
      POSTGRES_DB: vorarlberg_peaks
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
