import { PrismaClient, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

const regions = [
  {
    id: 'bregenzerwald',
    name: 'Bregenzerwald',
    nameDe: 'Bregenzerwald',
    description: 'Rolling pre-Alps with scenic valleys and the Vorarlberg highlands.',
  },
  {
    id: 'kleinwalsertal',
    name: 'Kleinwalsertal',
    nameDe: 'Kleinwalsertal',
    description: 'Secluded enclave valley accessible only from Germany, with rugged Allgäu peaks.',
  },
  {
    id: 'arlberg',
    name: 'Arlberg',
    nameDe: 'Arlberg',
    description: 'The legendary Arlberg massif, gateway between Vorarlberg and Tyrol.',
  },
  {
    id: 'montafon',
    name: 'Montafon',
    nameDe: 'Montafon',
    description: 'Long valley cut deep into the Central Alps, flanked by the Silvretta and Rätikon ranges.',
  },
  {
    id: 'silvretta',
    name: 'Silvretta',
    nameDe: 'Silvretta',
    description: 'High Alpine terrain on the border of Vorarlberg and Graubünden, with glaciers and 3000m peaks.',
  },
  {
    id: 'raetikon',
    name: 'Rätikon',
    nameDe: 'Rätikon',
    description: 'Dramatic limestone range along the Swiss and Liechtenstein border.',
  },
  {
    id: 'rheintal',
    name: 'Rhine Valley & Pfänder',
    nameDe: 'Rheintal & Pfänder',
    description: 'The flatlands and gentle hills bordering Lake Constance and the Rhine.',
  },
];

interface MountainSeed {
  name: string;
  nameDe?: string;
  altitude: number;
  latitude: number;
  longitude: number;
  regionId: string;
  difficulty: Difficulty;
  description?: string;
  externalId: string;
}

const mountains: MountainSeed[] = [
  // ── Bregenzerwald ────────────────────────────────────────────────────────
  {
    name: 'Kanisfluh',
    altitude: 1682,
    latitude: 47.3667,
    longitude: 9.9167,
    regionId: 'bregenzerwald',
    difficulty: 'moderate',
    description: 'Iconic table mountain above the Bregenzerwald with panoramic views over the Rhine Valley.',
    externalId: 'kanisfluh',
  },
  {
    name: 'Hoher Freschen',
    altitude: 2004,
    latitude: 47.3167,
    longitude: 9.7833,
    regionId: 'bregenzerwald',
    difficulty: 'moderate',
    description: 'Dominant peak above the Walgau valley, popular with families and experienced hikers alike.',
    externalId: 'hoher-freschen',
  },
  {
    name: 'Diedamskopf',
    altitude: 2090,
    latitude: 47.4167,
    longitude: 10.0167,
    regionId: 'bregenzerwald',
    difficulty: 'moderate',
    description: 'Well-known ski and hiking mountain in the Bregenzerwald, easily reached by lift in winter.',
    externalId: 'diedamskopf',
  },
  {
    name: 'Hochkünzelspitze',
    altitude: 2397,
    latitude: 47.3,
    longitude: 9.9333,
    regionId: 'bregenzerwald',
    difficulty: 'hard',
    description: 'Pointed summit requiring good route-finding skills on the ascent from Schoppernau.',
    externalId: 'hochkuenzelspitze',
  },
  {
    name: 'Mohnenfluh',
    altitude: 2542,
    latitude: 47.2667,
    longitude: 10.0,
    regionId: 'bregenzerwald',
    difficulty: 'hard',
    description: 'Prominent rocky peak on the boundary between Bregenzerwald and Arlberg regions.',
    externalId: 'mohnenfluh',
  },
  {
    name: 'Hochhäderich',
    altitude: 1565,
    latitude: 47.4333,
    longitude: 9.9667,
    regionId: 'bregenzerwald',
    difficulty: 'easy',
    description: 'A gentle summit perfect for families, with great views toward Lake Constance.',
    externalId: 'hochhaederich',
  },
  {
    name: 'Damülser Mittagsspitze',
    altitude: 2095,
    latitude: 47.2833,
    longitude: 9.8833,
    regionId: 'bregenzerwald',
    difficulty: 'moderate',
    description: 'Central summit of the Damüls area, reachable by a pleasant ridge walk.',
    externalId: 'damuelser-mittagsspitze',
  },
  {
    name: 'Braunarlspitze',
    altitude: 2649,
    latitude: 47.2667,
    longitude: 9.9667,
    regionId: 'bregenzerwald',
    difficulty: 'hard',
    description: 'Demanding high-alpine summit between Bregenzerwald and Arlberg, requiring surefootedness.',
    externalId: 'braunarlspitze',
  },
  {
    name: 'Winterstaude',
    altitude: 1878,
    latitude: 47.4667,
    longitude: 9.95,
    regionId: 'bregenzerwald',
    difficulty: 'easy',
    description: 'Popular family hike above Egg with sweeping views across the Bregenzerwald.',
    externalId: 'winterstaude',
  },

  // ── Kleinwalsertal ───────────────────────────────────────────────────────
  {
    name: 'Widderstein',
    altitude: 2533,
    latitude: 47.3667,
    longitude: 10.1667,
    regionId: 'kleinwalsertal',
    difficulty: 'hard',
    description: 'The most prominent summit of the Kleinwalsertal, with a steep final ridge requiring care.',
    externalId: 'widderstein',
  },
  {
    name: 'Hoher Ifen',
    altitude: 2230,
    latitude: 47.4167,
    longitude: 10.1333,
    regionId: 'kleinwalsertal',
    difficulty: 'moderate',
    description: 'Impressive limestone plateau rising above the Gottesacker — a geological wonder.',
    externalId: 'hoher-ifen',
  },
  {
    name: 'Elferkopf',
    altitude: 2387,
    latitude: 47.3667,
    longitude: 10.1833,
    regionId: 'kleinwalsertal',
    difficulty: 'moderate',
    description: 'Cable-car-served summit offering one of the finest ridge walks in the Allgäu Alps.',
    externalId: 'elferkopf',
  },
  {
    name: 'Zwölferkopf',
    altitude: 2224,
    latitude: 47.3583,
    longitude: 10.175,
    regionId: 'kleinwalsertal',
    difficulty: 'moderate',
    description: 'Neighbouring peak to the Elferkopf, linked by a spectacular high ridge trail.',
    externalId: 'zwoelferkopf',
  },
  {
    name: 'Hochvogel',
    altitude: 2592,
    latitude: 47.3833,
    longitude: 10.4333,
    regionId: 'kleinwalsertal',
    difficulty: 'expert',
    description: 'A classic expert summit on the border with Bavaria — a serious alpine undertaking with exposed passages.',
    externalId: 'hochvogel',
  },
  {
    name: 'Walmendinger Horn',
    altitude: 1990,
    latitude: 47.3917,
    longitude: 10.15,
    regionId: 'kleinwalsertal',
    difficulty: 'easy',
    description: 'Easily accessible summit with a revolving restaurant and family-friendly trails.',
    externalId: 'walmendinger-horn',
  },
  {
    name: 'Grünhorn',
    altitude: 2039,
    latitude: 47.3667,
    longitude: 10.2167,
    regionId: 'kleinwalsertal',
    difficulty: 'moderate',
    description: 'Green grassy summit above Baad, rewarding walkers with great views of the Widderstein.',
    externalId: 'gruenhorn-kleinwalsertal',
  },

  // ── Arlberg ──────────────────────────────────────────────────────────────
  {
    name: 'Valluga',
    altitude: 2809,
    latitude: 47.1667,
    longitude: 10.2167,
    regionId: 'arlberg',
    difficulty: 'expert',
    description: 'The iconic summit above St. Anton — the top station of the cable car, but the final ridge is for experienced alpinists only.',
    externalId: 'valluga',
  },
  {
    name: 'Trittkopf',
    altitude: 2722,
    latitude: 47.17,
    longitude: 10.2083,
    regionId: 'arlberg',
    difficulty: 'hard',
    description: 'High Arlberg summit with demanding terrain, excellent views toward the Silvretta.',
    externalId: 'trittkopf',
  },
  {
    name: 'Weißschrofenspitze',
    altitude: 2843,
    latitude: 47.1833,
    longitude: 10.25,
    regionId: 'arlberg',
    difficulty: 'expert',
    description: 'Remote and serious summit in the Lechtaler Alpen requiring alpine experience.',
    externalId: 'weissschrofenspitze',
  },
  {
    name: 'Rote Wand',
    altitude: 2704,
    latitude: 47.2167,
    longitude: 10.0167,
    regionId: 'arlberg',
    difficulty: 'hard',
    description: 'Striking red-hued summit above the turquoise Formarin See — one of Vorarlberg\'s most scenic hikes.',
    externalId: 'rote-wand-arlberg',
  },
  {
    name: 'Formaletschberg',
    altitude: 2436,
    latitude: 47.175,
    longitude: 10.15,
    regionId: 'arlberg',
    difficulty: 'moderate',
    description: 'Hike above the reservoir lake of Spullersee with great views across the Arlberg.',
    externalId: 'formaletschberg',
  },
  {
    name: 'Flexenspitze',
    altitude: 2628,
    latitude: 47.1583,
    longitude: 10.1333,
    regionId: 'arlberg',
    difficulty: 'hard',
    description: 'Prominent rocky peak above the famous Flexen Pass road.',
    externalId: 'flexenspitze',
  },

  // ── Montafon ─────────────────────────────────────────────────────────────
  {
    name: 'Zimba',
    altitude: 2643,
    latitude: 47.0667,
    longitude: 9.9333,
    regionId: 'montafon',
    difficulty: 'expert',
    description: 'The "Matterhorn of Vorarlberg" — a steep pyramid requiring confident scrambling and route-finding.',
    externalId: 'zimba',
  },
  {
    name: 'Golm',
    altitude: 2124,
    latitude: 47.05,
    longitude: 9.8833,
    regionId: 'montafon',
    difficulty: 'easy',
    description: 'Family-friendly mountain above Tschagguns, reachable by gondola with easy summit trails.',
    externalId: 'golm',
  },
  {
    name: 'Saulakopf',
    altitude: 2517,
    latitude: 46.9833,
    longitude: 10.0,
    regionId: 'montafon',
    difficulty: 'hard',
    description: 'Demanding summit in the upper Montafon on the border with Silvretta terrain.',
    externalId: 'saulakopf',
  },
  {
    name: 'Silberspitze',
    altitude: 2599,
    latitude: 47.0,
    longitude: 10.0333,
    regionId: 'montafon',
    difficulty: 'hard',
    description: 'High peak on the Silvretta-Montafon boundary with impressive glacier views.',
    externalId: 'silberspitze',
  },
  {
    name: 'Hochmaderer',
    altitude: 2781,
    latitude: 46.9667,
    longitude: 10.0167,
    regionId: 'montafon',
    difficulty: 'hard',
    description: 'Towering over the Versettla area, this summit requires stamina and sure-footedness.',
    externalId: 'hochmaderer',
  },
  {
    name: 'Kristberg',
    altitude: 1636,
    latitude: 47.0667,
    longitude: 9.9667,
    regionId: 'montafon',
    difficulty: 'easy',
    description: 'Sun-drenched terrace village above the Silbertal valley, ideal for easy walking tours.',
    externalId: 'kristberg',
  },
  {
    name: 'Versettlakopf',
    altitude: 2018,
    latitude: 47.0167,
    longitude: 9.9833,
    regionId: 'montafon',
    difficulty: 'moderate',
    description: 'Well-marked trails with gondola access in summer, offering great Montafon valley views.',
    externalId: 'versettlakopf',
  },
  {
    name: 'Hochjoch',
    altitude: 2520,
    latitude: 46.9583,
    longitude: 10.0083,
    regionId: 'montafon',
    difficulty: 'moderate',
    description: 'Classic high-alpine col linking Montafon and the Silvretta, with scenic glacier paths.',
    externalId: 'hochjoch-montafon',
  },

  // ── Silvretta ────────────────────────────────────────────────────────────
  {
    name: 'Piz Buin',
    altitude: 3312,
    latitude: 46.8417,
    longitude: 10.1167,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'The highest peak in Vorarlberg and a classic 3000m alpine objective, requiring crampons and glacier experience.',
    externalId: 'piz-buin',
  },
  {
    name: 'Dreiländerspitze',
    altitude: 3197,
    latitude: 46.8667,
    longitude: 10.0833,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'The "Three Countries Peak" at the junction of Austria, Switzerland and Liechtenstein — a serious high-alpine tour.',
    externalId: 'dreilaenderspitze',
  },
  {
    name: 'Silvrettahorn',
    altitude: 3244,
    latitude: 46.85,
    longitude: 10.1,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'Glacier summit adjacent to the Silvretta reservoir, requiring full alpine gear.',
    externalId: 'silvrettahorn',
  },
  {
    name: 'Großlitzner',
    altitude: 3109,
    latitude: 46.9,
    longitude: 10.0667,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'One of the classic 3000m Silvretta peaks, part of a long and rewarding high-alpine traverse.',
    externalId: 'grosslitzner',
  },
  {
    name: 'Piz Linard',
    altitude: 3411,
    latitude: 46.7667,
    longitude: 9.9833,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'Highest peak of the Lower Engadine, towering above the Silvretta region with challenging routes.',
    externalId: 'piz-linard',
  },
  {
    name: 'Lobspitze',
    altitude: 3031,
    latitude: 46.95,
    longitude: 10.0,
    regionId: 'silvretta',
    difficulty: 'expert',
    description: 'Demanding 3000m summit at the head of the Montafon valley, reserved for experienced alpinists.',
    externalId: 'lobspitze',
  },
  {
    name: 'Bielerhöhe',
    altitude: 2037,
    latitude: 46.9333,
    longitude: 10.1167,
    regionId: 'silvretta',
    difficulty: 'easy',
    description: 'Starting point for many Silvretta tours, with easy walks around the reservoir.',
    externalId: 'bielerhoehe',
  },

  // ── Rätikon ──────────────────────────────────────────────────────────────
  {
    name: 'Schesaplana',
    altitude: 2964,
    latitude: 47.0667,
    longitude: 9.7167,
    regionId: 'raetikon',
    difficulty: 'hard',
    description: 'The highest peak in the Rätikon, offering a classic route past the Lünersee and the famous Totalp Hut.',
    externalId: 'schesaplana',
  },
  {
    name: 'Drusenfluh',
    altitude: 2827,
    latitude: 47.0583,
    longitude: 9.7833,
    regionId: 'raetikon',
    difficulty: 'expert',
    description: 'Imposing limestone tower in the Rätikon, with one of the most challenging ascents in Vorarlberg.',
    externalId: 'drusenfluh',
  },
  {
    name: 'Sulzfluh',
    altitude: 2817,
    latitude: 47.0333,
    longitude: 9.7667,
    regionId: 'raetikon',
    difficulty: 'hard',
    description: 'Broad summit with a karst plateau, on the border with Switzerland\'s Prättigau.',
    externalId: 'sulzfluh',
  },
  {
    name: 'Drei Türme',
    altitude: 2826,
    latitude: 47.05,
    longitude: 9.75,
    regionId: 'raetikon',
    difficulty: 'expert',
    description: 'The "Three Towers" — a dramatic rock formation and one of the most iconic sights in the Rätikon.',
    externalId: 'drei-tuerme',
  },
  {
    name: 'Naafkopf',
    altitude: 2570,
    latitude: 47.0833,
    longitude: 9.5833,
    regionId: 'raetikon',
    difficulty: 'hard',
    description: 'Tripoint of Austria, Switzerland and Liechtenstein — a highly symbolic and scenic summit.',
    externalId: 'naafkopf',
  },
  {
    name: 'Totalp',
    altitude: 2385,
    latitude: 47.05,
    longitude: 9.7333,
    regionId: 'raetikon',
    difficulty: 'moderate',
    description: 'High plateau above the turquoise Lünersee, a magnificent and easily accessible tour.',
    externalId: 'totalp-raetikon',
  },
  {
    name: 'Kirchlispitzen',
    altitude: 2639,
    latitude: 47.0833,
    longitude: 9.7167,
    regionId: 'raetikon',
    difficulty: 'hard',
    description: 'Multi-summited ridge of rock towers offering an unforgettable traverse in the Rätikon.',
    externalId: 'kirchlispitzen',
  },
  {
    name: 'Garsellakopf',
    altitude: 2183,
    latitude: 47.1,
    longitude: 9.7,
    regionId: 'raetikon',
    difficulty: 'moderate',
    description: 'A classic Rätikon viewpoint above Bludenz, feasible as a half-day hike.',
    externalId: 'garsellakopf',
  },

  // ── Rhine Valley & Pfänder ───────────────────────────────────────────────
  {
    name: 'Pfänder',
    altitude: 1064,
    latitude: 47.5167,
    longitude: 9.7833,
    regionId: 'rheintal',
    difficulty: 'easy',
    description: 'Bregenz\'s beloved local mountain overlooking Lake Constance, accessible by cable car or forest trail.',
    externalId: 'pfaender',
  },
  {
    name: 'Gebhardsberg',
    altitude: 408,
    latitude: 47.505,
    longitude: 9.7483,
    regionId: 'rheintal',
    difficulty: 'easy',
    description: 'Short hike above Bregenz to the medieval castle ruin with fine views of Lake Constance.',
    externalId: 'gebhardsberg',
  },
  {
    name: 'Hirschberg',
    altitude: 1456,
    latitude: 47.4833,
    longitude: 9.7833,
    regionId: 'rheintal',
    difficulty: 'easy',
    description: 'Pleasant forested summit above the Rhine valley, popular as a weekend walk.',
    externalId: 'hirschberg-rheintal',
  },
  {
    name: 'Baumgartenschneid',
    altitude: 1621,
    latitude: 47.35,
    longitude: 9.9,
    regionId: 'rheintal',
    difficulty: 'moderate',
    description: 'A fine ridge walk above the Bregenzerach valley connecting the Bregenzerwald foothills.',
    externalId: 'baumgartenschneid',
  },
];

async function main() {
  console.log('Seeding regions...');
  for (const region of regions) {
    await prisma.region.upsert({
      where: { id: region.id },
      update: {},
      create: region,
    });
  }
  console.log(`  ✓ ${regions.length} regions`);

  // Filter out duplicated name overrides (TS allows it but we clean up)
  const uniqueMountains = mountains.filter(
    (m, i, arr) => arr.findIndex((x) => x.externalId === m.externalId) === i
  );

  console.log('Seeding mountains...');
  for (const m of uniqueMountains) {
    await prisma.mountain.upsert({
      where: { externalId: m.externalId },
      update: {
        name: m.name,
        altitude: m.altitude,
        latitude: m.latitude,
        longitude: m.longitude,
        difficulty: m.difficulty,
        description: m.description,
      },
      create: {
        name: m.name,
        nameDe: m.nameDe,
        altitude: m.altitude,
        latitude: m.latitude,
        longitude: m.longitude,
        regionId: m.regionId,
        difficulty: m.difficulty,
        description: m.description,
        externalId: m.externalId,
      },
    });
  }
  console.log(`  ✓ ${uniqueMountains.length} mountains`);
  console.log('Done!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
